blog/urls.py
from django.urls import path

from blog.views import blog, post

app_name = "blog"

urlpatterns = [path("", blog, name="index"), path("post/<int:id>/", post, name="post")]

home/urls.py
from django.urls import path

from home.views import home

app_name = "home"

urlpatterns = [path("", home, name="index")]

src/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("blog/", include("blog.urls")),
    path("", include("home.urls")),
]

blog/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

blog/views.py
import requests
from django.http import Http404
from django.shortcuts import render

POSTS_URL = "https://jsonplaceholder.typicode.com/posts"


def get_posts_data():
    data = requests.get(POSTS_URL).json()
    return data


def get_post_data(id: int) -> dict:
    data = requests.get(f"{POSTS_URL}/{id}").json()
    return data


def blog(request):
    return render(
        request, "blog/index.html", {"text": "BLOG", "posts": get_posts_data()}
    )


def post(request, id):
    post_data = get_post_data(id)
    if not post_data:
        raise Http404("Post does not exist")
    return render(request, "blog/post.html", {"text": f"POST {id}", "post": post_data})

home/views.py
from django.shortcuts import render


def home(request):
    return render(
        request,
        "index.html",
        context={"text": "I am at Home!", "title": "This is Home Page!"},
    )

blog/templates/blog/index.html
{% extends 'global/base.html' %}

{% if text %}
{% block texto %}
    {{ text }}
{% endblock texto %}
{% endif %}

{% block posts %}
    {% for post in posts %}
        {% include 'global/partials/post_block.html' %}
    {% endfor %}
{% endblock posts %}

blog/templates/blog/post.html
{% extends 'global/base.html' %}

{% if text %}
{% block texto %}
    {{ text }}
{% endblock texto %}
{% endif %}

{% block posts %}
    <article class="post single-post">
        <header>
            <h2 class="post__title">
                <a href="{% url 'blog:post' post.id %}">
                {{ post.title }}
                </a>
            </h2>
        </header>
        <div class="post__body">
            <p>
                {{ post.body }}
            </p>
        </div>
    </article>
{% endblock posts %}

home/templates/index.html
{% include 'global/base.html' %}

{% block texto %}
    {{ text }}
{% endblock texto %}

templates/global/base.html
<!DOCTYPE html>
<html lang="en">
{% include 'global/partials/head.html' %}
{% include 'global/partials/menu.html' %}
<body>
    <h1>{% block texto %}{% endblock texto %}</h1>

    <main class="content">
       {% block posts %}{% endblock posts %}
    </main>

</body>
</html>

templates/global/partials/head.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{% static 'global/css/style.css' %}">
</head>
</html>

templates/global/partials/menu.html
<nav class="menu">
    <ul class="menu__links">
        <li><a href="{% url 'home:index' %}">Home</a></li>
        <li><a href="{% url 'blog:index' %}">Blog</a></li>
    </ul>
</nav>

templates/global/partials/post_block.html
<article class="post">
    <header>
        <h2 class="post__title">
            <a href="{% url 'blog:post' post.id %}">
            {{ post.title }}
            </a>
        </h2>
    </header>
    <div class="post__body">
        <p>
            {{ post.body }}
        </p>
    </div>
</article>